### ISSUE TITLE
No longer able DAG to update via AirFlow

### ISSUE THREAD

**Issue by twointum** [sungchun12/airflow-dbt-cloud#1]
Hello! I am getting the following error: 

```
   return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/var/www/html/python/DAGs/dbt_cloud_utils.py", line 110, in run_job
    job_run_id = self._trigger_job()
  File "/var/www/html/python/DAGs/dbt_cloud_utils.py", line 77, in _trigger_job
    assert self.account_id == response_payload["data"]["account_id"]
TypeError: 'NoneType' object is not subscriptable
[2022-02-27, 16:01:38 PST] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-02-27, 16:01:39 PST] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

Do you know what would cause this error now? I recently had my trial expire but I just switched it to developer to continue my tests. I ran the DBT job successfully in the cloud web app, but my DAG no longer runs.  Maybe the response changed? I'm not skilled enough to determine :(

Thank you.

**Comment by twointum** [comment]
Nevermind, I printed the response payload and see the issue :(

`[2022-02-27, 17:23:29 PST] {logging_mixin.py:109} INFO - {'status': {'code': 401, 'is_success': False, 'user_message': 'The API is not accessible to unpaid accounts.', 'developer_message': None}, 'data': None}`

**Comment by sungchun12** [comment]
Thanks for detailing it out in this issue! Let me know if you need any help otherwise.

I'll go ahead and close this issue!
