### ISSUE TITLE
Include link back to dbt cloud job for dbt Cloud Provider 

### ISSUE THREAD

**Issue by belasobral93** [sungchun12/airflow-dbt-cloud#8]
I noticed that the task logs using dbt Cloud Operators (in [dbt_cloud_provider_example.py](https://github.com/sungchun12/airflow-dbt-cloud/blob/main/dags/dbt_cloud_provider_example.py)) don't print a url taking the user back to the dbt cloud UI (like [cloud_example.py](https://github.com/sungchun12/airflow-dbt-cloud/blob/main/dags/dbt_cloud_example.py) does) - would be great to include this to further enable sql analysts to troubleshoot their cloud jobs, reducing dependencies on data engineers. 

(I couldn't figure out how to add to the operator without causing a syntax error either with print() or jinja's do log)

**Comment by sungchun12** [comment]
@belasobral93 are you able to click on the task and click the `Monitor Run` button?
![image](https://user-images.githubusercontent.com/19176976/162979121-234f294d-8d04-4f3b-9633-70658150a9e6.png)

You can see the loom video [here](https://www.loom.com/share/8214136dd9ca4208b7e6c38ea79d70ad) for a live demo to see if there's something tacit to learn from!

**Comment by belasobral93** [comment]
yes!! I was using "Log" exclusively. thanks for the video
